In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from IPython.display import Image

## ## 데이터 불러오기

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/머신러닝/2조_머신러닝_미니프로젝트/res/raw_data/20년 KBO리그.csv',
                 index_col=0)

df

,연도,팀명,G,W,D,L,WPCT,R,R(A),RD,...,PB,SB,CS,CS%,SBA(R),SB(R),CS(R),SB(R)%,OOB,PKO(R)
0,2001,KIA,133,60,5,68,0.469,683,727,-44,...,10,100,53,34.6,155,92,63,59.4,0,0
1,2001,LG,133,58,8,67,0.464,669,732,-63,...,16,110,55,33.3,154,96,58,62.3,0,0
2,2001,SK,133,60,2,71,0.458,596,640,-44,...,19,106,44,29.3,182,123,59,67.6,0,0
3,2001,두산,133,65,5,63,0.508,732,733,-1,...,12,126,56,30.8,166,132,34,79.5,0,0
4,2001,롯데,133,59,4,70,0.457,718,670,48,...,12,85,58,40.6,159,106,53,66.7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,2021,두산,144,71,8,65,0.522,738,656,82,...,10,83,48,36.6,118,81,37,68.6,48,11
180,2021,롯데,144,65,8,71,0.478,727,808,-81,...,8,101,44,30.3,91,60,31,65.9,54,8
181,2021,삼성,144,76,9,59,0.563,712,658,54,...,5,61,26,29.9,160,116,44,72.5,47,7
182,2021,키움,144,70,7,67,0.511,722,700,22,...,5,85,35,29.2,123,97,26,78.9,39,3
183,2021,한화,144,49,12,83,0.371,599,739,-140,...,7,111,41,27.0,165,109,56,66.1,59,14

# # 머신러닝 준비

## ## 쓰이는 함수 정리
  * [map(), lambda](https://wikidocs.net/64)
    - map(첫 번째 매개변수, 두 번째 매개변수)
      + 첫 번째 매개변수로는 함수가 오고
      + 두 번째 매개변수로는 반복 가능한 자료형 (출처: https://blockdmask.tistory.com/531 [개발자 지망생])

In [ ]:
df['WIN']

0      N
1      N
2      N
3      Y
4      N
      ..
179    N
180    N
181    N
182    N
183    N
Name: WIN, Length: 184, dtype: object

## ## 데이터 정제
  * 'WIN'컬럼, 'POST'컬럼 데이터를 알고리즘 처리에 적합하게 정제
  * target 데이터가 1,0으로 바꾸기
    - Y = 1
    - N = 0

In [ ]:
df['WIN'] = df['WIN'].map(lambda x : 0 if x == 'N' else 1)

In [ ]:
df['WIN']

0      0
1      0
2      0
3      1
4      0
      ..
179    0
180    0
181    0
182    0
183    0
Name: WIN, Length: 184, dtype: int64

## ## target 데이터 변수 설정

In [ ]:
win_y = df['WIN']

## ## 사용할 컬럼 설정
  * 데이터 분석 결과 최종 사용할 컬럼 선정

In [ ]:
features = ['AVG', 'OPS', 'RISP', 'ERA', 'WHIP', 'FPCT']

In [ ]:
# 전체 팀 기록에서 필요한 컬럼만 선정
ratio_X = df[features]

In [ ]:
ratio_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 184 entries, 0 to 183
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AVG     184 non-null    float64
 1   OPS     184 non-null    float64
 2   RISP    184 non-null    float64
 3   ERA     184 non-null    float64
 4   WHIP    184 non-null    float64
 5   FPCT    184 non-null    float64
dtypes: float64(6)
memory usage: 10.1 KB

In [ ]:
ratio_X.head()

     AVG    OPS   RISP   ERA  WHIP   FPCT
0  0.278  0.781  0.272  5.01  1.47  0.979
1  0.276  0.754  0.280  5.09  1.60  0.980
2  0.260  0.728  0.255  4.38  1.41  0.981
3  0.276  0.780  0.278  4.96  1.56  0.979
4  0.280  0.790  0.288  4.68  1.50  0.981